version: 2
jobs:
  build:
    docker:
      - image: cucumber/cucumber-build:23411e87fd71966bdf7217d36fb581cf

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: make

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
